shallow_clone: true

image: Visual Studio 2013
platform:
  - x86
  - x64

environment:
  matrix:
    - VSVER: 12

install:
  - ps: >-
      If ($env:Platform -Match "x86") {
          $env:VCVARS_PLATFORM="x86"
          $env:X=""
          $env:BUILD="x86-pc-cygwin"
          $env:HOST="x86-pc-windows"
        } Else {
          $env:VCVARS_PLATFORM="amd64"
          $env:X="-m64"
          $env:BUILD="x86_64-pc-cygwin"
          $env:HOST="x86_64-pc-winnt"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

build_script:
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./autogen.sh;)"
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./configure CC='/cygdrive/c/projects/libffi/msvcc.sh $X' CXX='/cygdrive/c/projects/libffi/msvcc.sh $X' LD=link CPP='cl -nologo -EP' --build=$BUILD --host=$HOST; cp src/x86/ffitarget.h include; make)"
  




  
  

  

  
  

  
  

