language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      compiler: gcc
      env: HOST=i386-pc-linux-gnu
    - os: linux
      compiler: gcc
      env: HOST=i686-w64-mingw32 RUNTESTFLAGS="--target_board wine-sim ${expfile}" DEJAGNU=`pwd`/.travis/site.exp DISPLAY=:99.0 WINEDEBUG=fixme-all

install:
  - ./.travis/install.sh

script:
  - ./autogen.sh
  - if test x"$HOST" = x"i386-pc-linux-gnu"; then CC="$CC -m32"; CXX="$CXX -m32"; fi
  - if test x"$HOST" = x"i686-w64-mingw32"; then CC="i686-w64-mingw32-gcc"; CXX="i686-w64-mingw32-g++"; sh -e /etc/init.d/xvfb start; sleep 3; fi
  - ./configure ${HOST+--host=$HOST}
  - make
  - make dist
  - make check RUNTESTFLAGS="$RUNTESTFLAGS"
  - cat */testsuite/libffi.log
