shallow_clone: true

os: Visual Studio 2015
platform:
  - x86
  - x64

build_script:
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./autogen.sh;)"
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./configure CC='/cygdrive/c/projects/libffi/msvcc.sh' CXX='/cygdrive/c/projects/libffi/msvcc.sh' LD=link CPP='cl -nologo -EP'; cat `find ./ -name config.log`)"
  - c:\cygwin\bin\sh -lc "find /cygdrive/c"

  
  

  
  

