shallow_clone: true

image: Visual Studio 2013
platform:
  - x86
  - x64

environment:
  matrix:
    - VSVER: 12

install:
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

build_script:
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./autogen.sh;)"
  - c:\cygwin\bin\sh -lc "(cd $OLDPWD; ./configure CC='/cygdrive/c/projects/libffi/msvcc.sh -m64' CXX='/cygdrive/c/projects/libffi/msvcc.sh -m64' LD=link CPP='cl -nologo -EP' --build=x86_64-pc-cygwin --host=x86_64-pc-winnt; cp src/x86/ffitarget.h include; make)"
  - c:\cygwin\bin\sh -lc "env"
  - set
  




  
  

  

  
  

  
  

